# Generated by Django 5.2.9 on 2025-12-05 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('min_unt_score', models.IntegerField()),
                ('languages', models.CharField(max_length=400)),
                ('tuition_fee', models.IntegerField()),
                ('internships', models.BooleanField(default=True)),
                ('scholarships', models.BooleanField(default=True)),
                ('image_url', models.URLField()),
                ('majors', models.ManyToManyField(related_name='universities', to='webapp.major')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.type')),
            ],
        ),
    ]
