# Generated by Django 5.2.9 on 2025-12-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='uni_tour',
            field=models.URLField(blank=True, null=True),
        ),
    ]
