# Generated by Django 5.2.9 on 2025-12-06 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_surveyresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questions',
            name='question_type',
            field=models.CharField(choices=[('single', 'Один вариант'), ('multiple', 'Несколько вариантов'), ('text', 'Текстовый ответ')], default='single', max_length=20),
        ),
    ]
