# Generated by Django 5.2.9 on 2025-12-06 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_questions_order_questions_question_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyresponse',
            name='question',
        ),
    ]
